# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-04-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20260415_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longfailedarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('ar', 'Arabic'), ('uk', 'Ukrainian'), ('dsb', 'Lower Sorbian'), ('sv', 'Swedish'), ('ru', 'Russian')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='recursionerrorarticle',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('ar', 'Arabic'), ('uk', 'Ukrainian'), ('dsb', 'Lower Sorbian'), ('sv', 'Swedish'), ('ru', 'Russian')], default='', max_length=8),
        ),
    ]
