# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-05-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0033_auto_20260506_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('ar', 'Arabic'), ('uk', 'Ukrainian'), ('dsb', 'Lower Sorbian'), ('sv', 'Swedish'), ('ru', 'Russian'), ('hi', 'Hindi'), ('fa', 'Persian'), ('zh', 'Chinese'), ('vi', 'Vietnamese'), ('ce', 'Chechen'), ('sr', 'Serbian'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('cs', 'Czech'), ('ro', 'Romanian'), ('sh', 'Serbo-Croatian')], default='', max_length=8),
        ),
    ]
